# Generated by Django 4.2.29 on 2026-03-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wife",
            name="husband",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="relations.husband"
            ),
        ),
    ]
