# Generated by Django 4.2.29 on 2026-03-29 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campsite_name", models.CharField(max_length=60)),
                ("arrival", models.DateTimeField()),
                ("departure", models.DateTimeField()),
                ("email", models.EmailField(max_length=254)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
