# Generated by Django 4.2.29 on 2026-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
