# Generated by Django 4.2.29 on 2026-04-10 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("camps", "0002_booking_guests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="campsite",
            options={
                "ordering": ["name"],
                "verbose_name": "Campsite",
                "verbose_name_plural": "Campsites",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="campsite",
            field=models.ForeignKey(
                help_text="Campsite being booked",
                on_delete=django.db.models.deletion.CASCADE,
                to="camps.campsite",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(help_text="End date of the booking"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(help_text="Number of guests"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(help_text="Start date of the booking"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the booking",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campsite",
            name="capacity",
            field=models.IntegerField(help_text="Maximum number of guests"),
        ),
        migrations.AlterField(
            model_name="campsite",
            name="name",
            field=models.CharField(help_text="Name of the campsite", max_length=100),
        ),
        migrations.AlterField(
            model_name="campsite",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2, help_text="Price per night in USD", max_digits=6
            ),
        ),
    ]
