# Generated by Django 4.2.29 on 2026-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=60)),
                ("post_content", models.TextField()),
                ("published_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
