# Generated by Django 4.2.29 on 2026-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_auther",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
