# Generated by Django 4.2.29 on 2026-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_post_auther"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateField(auto_now=True),
        ),
    ]
